# Generated by Django 4.2.7 on 2025-08-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('ai_confidence', models.IntegerField(default=0)),
                ('ai_issues', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('VALIDATE', 'Validate'), ('STATUS_CHANGE', 'Status Change')], max_length=20)),
                ('actor', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
