# Generated by Django 4.2.7 on 2025-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='enc_alg',
            field=models.CharField(default='AES-256-GCM', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='enc_iv',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='document',
            name='enc_tag',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_backend',
            field=models.CharField(default='LOCAL', max_length=10),
        ),
    ]
